[package]
name = "aggregation-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.7"
gdal = "0.14.0"
geo-rasterize = "0.1.2"
geo-types = "0.7.8"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
netcdf = "0.7.0"
rayon = "1.6.1"
shapefile = {version = "0.3.0", features = ["geo-types"]}
