name: Build and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Store Wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Maturin
        run: pip install maturin

      - name: Build Wheels
        run: maturin build --release --out target/wheels/

      - name: Upload Wheels as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: target/wheels/

      - name: Upload Wheels to GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: target/wheels/*.whl
          tag_name: ${{ github.ref_name }}
          body: "🚀 Pre-built wheels for risico_aggregation."
          draft: false
          prerelease: false
